create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table contact_messages enable row level security;

drop policy if exists "Anyone can send contact messages" on contact_messages;
create policy "Anyone can send contact messages"
on contact_messages for insert
to anon, authenticated
with check (
  length(trim(name)) between 2 and 120
  and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
  and length(trim(message)) between 2 and 3000
);

drop policy if exists "Admins can read contact messages" on contact_messages;
create policy "Admins can read contact messages"
on contact_messages for select
to authenticated
using (
  exists (
    select 1
    from profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
  )
);

drop policy if exists "Admins can delete contact messages" on contact_messages;
create policy "Admins can delete contact messages"
on contact_messages for delete
to authenticated
using (
  exists (
    select 1
    from profiles
    where profiles.id = auth.uid()
      and profiles.role = 'admin'
  )
);
